# Catalogue Management Service Restful APIs
info:
  app:
    name: Catalogue Management System
    description: Catalogue Management System REST APIs Using Spring-Webflux
    version: 1.0.0
server:
  port: 8081
# Spring boot actuator configurations
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
logging:
  level:
    root: INFO
    com.toomuch2learn: DEBUG
    org.springframework: INFO
    org.apache.catalina: ERROR

spring:
  resources:
    add-mappings: false
  h2:
    console:
      enabled: true
      path: /h2

  # R2DBC Configuration
  r2dbc:
    url: r2dbc:h2:mem:///cataloguedb
    username: 'sa'
    password: ''
    initialization-mode: always
  datasource:
    url: 'jdbc:h2:mem:cataloguedb'
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''