# Catalogue Management Service Restful APIs
info:
  app:
    name: Catalogue Management System
    description: Catalogue Management System REST APIs Using Spring-Webflux
    version: 1.0.0

server:
  port: 8081
# Spring boot actuator configurations
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
# Datasource Configurations
h2:
  console:
    enabled: true
    path: /h2

# R2DBC Configuration
r2dbc:
  url: r2dbc:h2:mem:///cataloguedb
  username: sa
  password:
  initialization-mode: always

